# Site settings
title: Alpha
baseurl: "/alpha" # the subpath of your site, e.g. /blog/
url: "http://localhost" # the base hostname & protocol for your site

exclude: ["design"]

# Markdown
markdown: kramdown

kramdown:
  input: GFM

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "docs/api"
    values:
      section: "api"
  -
    scope:
      path: "docs/intro"
    values:
      section: "intro"